// Cross-implementation parity tests for the FMDN crypto stack.
//
// The vectors below are copied verbatim from the Rust oracle
// `desktop-app/src/crypto.rs::tests` (which in turn were generated by running
// the GoogleFindMyTools Python reference once). If the TS port drifts from the
// Rust/Python algorithm, these go red. See docs/desktop-app-crypto.md.

import { describe, it, expect } from 'vitest';
import { gcm } from '@noble/ciphers/aes.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { calculateR, rxToRy } from '../lib/fmdn/secp160r1';
import { decryptEik, flipBits } from '../lib/fmdn/eik';
import {
  decryptOwnReport,
  decryptForeignReport,
  decodeLocation,
} from '../lib/fmdn/report';
import { PbWriter } from '../lib/fmdn/protobuf';

function hex(h: string): Uint8Array {
  const a = new Uint8Array(h.length / 2);
  for (let i = 0; i < a.length; i++) a[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return a;
}
function toHex(b: Uint8Array): string {
  return Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('');
}

/** AES-GCM encrypt into the IV||ct||tag layout the decryptor expects (test helper). */
function aesGcmEncrypt(key: Uint8Array, iv: Uint8Array, plaintext: Uint8Array): Uint8Array {
  const ctAndTag = gcm(key, iv).encrypt(plaintext);
  const out = new Uint8Array(iv.length + ctAndTag.length);
  out.set(iv, 0);
  out.set(ctAndTag, iv.length);
  return out;
}

/** Encode a Location protobuf (sfixed32 lat=1, sfixed32 lon=2, int32 alt=3). */
function encodeLocation(latE7: number, lonE7: number, alt: number): Uint8Array {
  return new PbWriter().fixed32(1, latE7).fixed32(2, lonE7).int(3, alt).finish();
}

describe('calculate_r (parity with crypto.rs)', () => {
  it('matches Python reference vector 1', () => {
    const k = hex('aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899');
    expect(calculateR(k, 0x0084d000).toString(16)).toBe('a2582350a17446440784a69c5cc6efa71ff4f28c');
  });
  it('matches Python reference vector 2', () => {
    const k = hex('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff');
    expect(calculateR(k, 0).toString(16)).toBe('96d4399fdee5701cae701a66f48595c47d1cfe93');
  });
});

describe('rx_to_ry (SECP160R1 point recovery)', () => {
  it('recovers the even Gy from Gx', () => {
    const gx = 0x4a96b5688ef573284664698968c38bb913cbfc82n;
    const gy = rxToRy(gx);
    expect(gy.toString(16)).toBe('23a628553168947d59dcc912042351377ac5fb32');
    expect(gy % 2n).toBe(0n);
  });
  it('rejects an x not on the curve', () => {
    expect(() => rxToRy(1n)).toThrow();
  });
});

describe('decrypt_eik', () => {
  it('AES-GCM 60-byte round-trip', () => {
    const ownerKey = new Uint8Array(16).fill(0xab);
    const eik = new Uint8Array(32).fill(0x42);
    const blob = aesGcmEncrypt(ownerKey, new Uint8Array(12).fill(0x01), eik);
    expect(blob.length).toBe(60);
    expect(toHex(decryptEik(ownerKey, blob, false))).toBe(toHex(eik));
  });

  it('is_mcu un-flips before decrypting', () => {
    const ownerKey = new Uint8Array(16).fill(0xab);
    const eik = new Uint8Array(32).fill(0x99);
    const plainBlob = aesGcmEncrypt(ownerKey, new Uint8Array(12).fill(0x02), eik);
    const flipped = flipBits(plainBlob);
    expect(() => decryptEik(ownerKey, flipped, false)).toThrow(); // tag mismatch on flipped bytes
    expect(toHex(decryptEik(ownerKey, flipped, true))).toBe(toHex(eik));
  });

  it('rejects an unexpected length', () => {
    expect(() => decryptEik(new Uint8Array(16), new Uint8Array(32), false)).toThrow(/length 32/);
  });

  it('flip_bits matches the Python XOR 0xFF', () => {
    expect(toHex(flipBits(hex('0001feffab')))).toBe('fffe010054');
  });
});

describe('decrypt_own_report', () => {
  it('round-trips SF coordinates (key = SHA256(EIK))', () => {
    const eik = new Uint8Array(32).fill(0x37);
    const key = sha256(eik);
    const plain = encodeLocation(377_749_000, -1_224_194_000, 15);
    const blob = aesGcmEncrypt(key, new Uint8Array(12).fill(0x07), plain);
    const loc = decryptOwnReport(eik, blob);
    expect(loc.latitude).toBeCloseTo(37.7749, 9);
    expect(loc.longitude).toBeCloseTo(-122.4194, 9);
    expect(loc.altitudeM).toBe(15);
  });
  it('rejects a truncated blob', () => {
    expect(() => decryptOwnReport(new Uint8Array(32), new Uint8Array(10))).toThrow();
  });
});

describe('decrypt_foreign_report (end-to-end SECP160R1 ECIES parity)', () => {
  it('Python vector 1 → 37.7749, -122.4194, 15m', () => {
    const k = hex('aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899');
    const ct = hex('358d966e689af0b0f3199fa43885c01862fbab8fd6bc1bbccd769b89');
    const sx = hex('dde7ecd33c015ba08035f8fa977bc8b2bc8387be');
    const loc = decryptForeignReport(k, ct, sx, 0x0084d000);
    expect(loc.latitude).toBeCloseTo(37.7749, 9);
    expect(loc.longitude).toBeCloseTo(-122.4194, 9);
    expect(loc.altitudeM).toBe(15);
  });

  it('Python vector 2 → 51.1234567, -7.654321, 30m', () => {
    const k = hex('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff');
    const ct = hex('12dc5a6b22629bf275d92b211063a0505be2ce760b6849532cefc87b');
    const sx = hex('d72519786b0430734453d748c8351f867d57ad0e');
    const loc = decryptForeignReport(k, ct, sx, 0);
    expect(loc.latitude).toBeCloseTo(51.1234567, 9);
    expect(loc.longitude).toBeCloseTo(-7.654321, 9);
    expect(loc.altitudeM).toBe(30);
  });

  it('rejects a blob shorter than the 16-byte tag', () => {
    expect(() => decryptForeignReport(new Uint8Array(32), new Uint8Array(8), hex('010203'), 0)).toThrow();
  });
  it('rejects empty public_key_random', () => {
    expect(() => decryptForeignReport(new Uint8Array(32), new Uint8Array(32), new Uint8Array(0), 0)).toThrow();
  });
  it('rejects a tampered ciphertext (EAX tag check)', () => {
    const k = hex('aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899');
    const ct = hex('358d966e689af0b0f3199fa43885c01862fbab8fd6bc1bbccd769b89');
    ct[0] ^= 0x01;
    const sx = hex('dde7ecd33c015ba08035f8fa977bc8b2bc8387be');
    expect(() => decryptForeignReport(k, ct, sx, 0x0084d000)).toThrow(/tag mismatch/);
  });
});

describe('decodeLocation', () => {
  it('skips unknown fields', () => {
    const base = encodeLocation(123_456_700, -98_765_400, 42);
    const withUnknowns = new Uint8Array([...base, 0x98, 0x06, 0x7f, 0xa2, 0x06, 0x03, 97, 98, 99]);
    const loc = decodeLocation(withUnknowns);
    expect(loc.latitude).toBeCloseTo(12.34567, 9);
    expect(loc.longitude).toBeCloseTo(-9.87654, 9);
    expect(loc.altitudeM).toBe(42);
  });
  it('throws when latitude is missing', () => {
    const noLat = new PbWriter().fixed32(2, 100).int(3, 5).finish();
    expect(() => decodeLocation(noLat)).toThrow(/latitude/);
  });
});
